### ISSUE TITLE
Integration of Python hints

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#87] opened 2023-10-03 14:19 UTC

**Comment by rodrigo-pino** [comment] 2023-10-08 22:08
As part of completing the Cairo Zero Runner we need to be able to run Python hints. The issue is that Go Language doesn't understand Python and our VM works a little different from it as well.

This issue is for discussing ideas on different ways of solving this and take the best of them.

**Comment by rodrigo-pino** [comment] 2023-10-08 22:38
One approach is to studay all possible Python hints that the Compiler can produce since there is a finite amount. Implement a mechanism to detect this hints. It will need to gather the following information:

* The type of hint: allocating a new segment, finding the square root, asserting that a number is lower than other, etc..
* What does this hints requires to function. For example, the `AllocSegment` hint in python is represented as:
```json
{
    "accessible_scopes": [
        "starkware.cairo.common.alloc",
        "starkware.cairo.common.alloc.alloc"
    ],
    "code": "memory[ap] = segments.add()", 
    "flow_tracking_data": {
        "ap_tracking": {
            "group": 2,
            "offset": 0
        },
        "reference_ids": {}
    }
}
```
We can infer that we want to allocate a new segment  by just the code itself. `accesible_scopes` are not required and I am not sure about `ap_tracking`. Should investigate a little more about that, but they don't seem essential.

Custom python hints are not a priority since Cairo Zero shouldn't be used anymore. So this approach would not support them

**Comment by rodrigo-pino** [comment] 2023-10-09 00:29
### The idea
One approach is to study and gather all possible Python hints that the Compiler can produce since there is a finite amount. Implement a mechanism to detect hints. If these hints are all the same then a simple string matching will suffice, if they are different then a more complex mechanism is required.

Once a hint is detected, meaning we know what type of hint it is(e.g. allocating a new segment, finding the square root, asserting that a number is lower than other, etc.) we need to extract the information required to make it work. Then we create a Go Structure which holds this information and is easy for the VM to interact with.

### Example 1
Trying to ground the idea a little, I'll  describe it using examples. Let's start with a simple example, the `AllocSegment` hint in python is represented as:
```json
{
    "accessible_scopes": [
        "starkware.cairo.common.alloc",
        "starkware.cairo.common.alloc.alloc"
    ],
    "code": "memory[ap] = segments.add()", 
    "flow_tracking_data": {
        "ap_tracking": {
            "group": 2,
            "offset": 0
        },
        "reference_ids": {}
    }
}
```
We can infer that we want to allocate a new segment  by just the `code` itself.  Neither`accesible_scopes` or `ap_tracking_data`(?) are required:

* `accesible_scopes` determines the imports required by `code`.
* `ap_tracking_data` has a _group_ and an _offset_. It is used to track the `ap` change between different references. If two references have different groups it means that `ap` cannot be deduced because of an unknown change. If they have the same group then the offset value establish the difference between the `ap` value at both instructions. I currently don't see how this information could affect the runner.

With this info we define a Go structure which is capable of representing an `AllocSegment` hint:
https://github.com/NethermindEth/cairo-vm-go/blob/c65b6b207b24cdd5e2461971be8e27ec0b5d659c/pkg/hintrunner/hint.go#L17-L19

We only need a destination and it is marked as a cell reference, which means, a memory address, in this case "ap + 0". After parsing the info, we should then execute:
```go
hint := AllocSegment { dst: ApCellRef(0) }
```

### Example 2
Looking at a more complex example: a hint that compares that certain value is in a certain range:
```json
{
    "accessible_scopes": [
        "starkware.cairo.common.math",
        "starkware.cairo.common.math.assert_nn"
    ],
    "code": "from starkware.cairo.common.math_utils import assert_integer\nassert_integer(ids.a)\nassert 0 <= ids.a % PRIME < range_check_builtin.bound, f'a = {ids.a} is out of range.'",
    "flow_tracking_data": {
        "ap_tracking": {
            "group": 4,
            "offset": 0
        },
        "reference_ids": {
            "starkware.cairo.common.math.assert_nn.a": 9,
            "starkware.cairo.common.math.assert_nn.range_check_ptr": 10
        }
    }
}
```
Just like the previous example we can detect by the code what type of hint we want to execute and `ap_tracking_data` also seems to be of no use. Unlike the previous example this hint uses some extra information. The code references values and in `reference_ids` we find:
```json
"reference_ids": {
      "starkware.cairo.common.math.assert_nn.a": 9,
      "starkware.cairo.common.math.assert_nn.range_check_ptr": 10
}
```
This field holds the values required by the hint to work properly. Each entry has a unique name and a unique integer assigned to it. The name tell us where to find the value using the `identifiers` field of the compiled file. 
If we search for _"starkware.cairo.common.math.assert_nn.a"_ we get to:
```json
"starkware.cairo.common.math.assert_nn.a": {
    "cairo_type": "felt",
    "full_name": "starkware.cairo.common.math.assert_nn.a",
    "references": [
        {
            "ap_tracking_data": {
                "group": 4,
                "offset": 0
            },
            "pc": 15,
            "value": "[cast(fp + (-3), felt*)]"
        }
    ],
    "type": "reference"
}
```
This is a **Reference** which is defined for a specific location in the program (pc). It has a couple of fields but the one we care the most is the one at `value`. Which is  from inner expression to outermost expression: 

1.  "cast(fp + (-3), felt*)" ->  treat the result of "fp - 3" as a memory address (or pointer)
2.  "[ cast(fp + (-3), felt*) ]" -> give me the value held at that address.

Looking for the remaining identifier, we get the following information which is very similar to what we've already seen.
```json
"starkware.cairo.common.math.assert_nn.range_check_ptr": {
    "cairo_type": "felt",
    "full_name": "starkware.cairo.common.math.assert_nn.range_check_ptr",
    "references": [
        {
            "ap_tracking_data": {
                "group": 4,
                "offset": 0
            },
            "pc": 15,
            "value": "[cast(fp + (-4), felt*)]"
        },
        {
            "ap_tracking_data": {
                "group": 4,
                "offset": 0
            },
            "pc": 16,
            "value": "cast([fp + (-4)] + 1, felt)"
        }
    ],
    "type": "reference"
},
```
The only difference is that there are two references using different `pc`. I am not sure why this is happening but I guess the value varies depending on the current instruction (`pc`) the VM is standing on. The first reference value is read similar to the previous reference id. The second reference value is read as:

1. Give me the value at "[fp + (-4)]"
2. Increase it by one "[fp + (-4)] + 1"
3. Treat it as a felt (and not as a memory address/pointer) "cast([fp + (-4) + 1, felt)"

I think it is worth investigating into this... the Cairo 0 compiler output is full of mysteries.

The remaining step is to translate this as Go information. **Note** that a one to one direct translation may not be the best way to write the Go hint representation for the VM. Since both VMs have their differences beyond being on a different programming languages. 

### Sum Up

What we should do is:

1. Detect the hint type using the code.
2. Gather the information using the references ids.
3. Translate this information to Go.

Doing this for every hint will solve this issue. The only remaining step which will come later is to actually implement the hint in Go using the implemented structure. The expected structure should be similar to what we already have, which is compatible to how the latest compiler version marks its hints.

https://github.com/NethermindEth/cairo-vm-go/blob/c65b6b207b24cdd5e2461971be8e27ec0b5d659c/pkg/hintrunner/hint.go#L42-L46

**Note** that custom python hints are not a priority since Cairo Zero shouldn't be used anymore. So this approach would not support them

### Extra

The code I used to make the following example is the following in case anyone wants to replicate it:

```py
%builtins output range_check bitwise

from starkware.cairo.common.cairo_keccak.keccak import _keccak
from starkware.cairo.common.cairo_builtins import BitwiseBuiltin
from starkware.cairo.common.alloc import alloc
from starkware.cairo.common.serialize import serialize_word

func fill_array(array: felt*, base: felt, array_length: felt, iterator: felt) {
    if (iterator == array_length) {
        return ();
    }

    assert array[iterator] = base;

    return fill_array(array, base, array_length, iterator + 1);
}

func main{output_ptr: felt*, range_check_ptr, bitwise_ptr: BitwiseBuiltin*}() {
    alloc_locals;

    let (output: felt*) = alloc();
    let keccak_output = output;

    let (inputs: felt*) = alloc();
    let inputs_start = inputs;
    fill_array(inputs, 9, 3, 0);

    let (state: felt*) = alloc();
    let state_start = state;
    fill_array(state, 5, 25, 0);

    let n_bytes = 24;

    let (res: felt*) = _keccak{keccak_ptr=keccak_output}(
        inputs=inputs_start, n_bytes=n_bytes, state=state_start
    );

    serialize_word(res[0]);
    serialize_word(res[1]);
    serialize_word(res[2]);
    serialize_word(res[4]);

    return ();
}
```

**Comment by quasilyte** [comment] 2024-01-11 11:43
How would we handle a function like this:
```
func dict_new() -> (res: DictAccess*) {
    %{
        if '__dict_manager' not in globals():
            from starkware.cairo.common.dict import DictManager
            __dict_manager = DictManager()

        memory[ap] = __dict_manager.new_dict(segments, initial_dict)
        del initial_dict
    %}
    ap += 1;
    return (res=cast([ap - 1], DictAccess*));
}
```

Both old (cairo0) and new Cairo compilers produce something like this when handling dictionaries.

This PR implements some of the functionality that is used inside the Python-style hint:
https://github.com/NethermindEth/cairo-vm-go/pull/146

So am I right that the plan is to match this whole block of code and emit a hint that is implemented inside our Go code?

**Comment by quasilyte** [comment] 2024-01-17 07:49
For multi-statement hints that are hard to translate into our hints, instead of creating dedicated hints for the whole thing we can recognize some of the cairo stdlib functions and map them to our Go implementations.
This way, instead of matching almost arbitrary Python code (like in `dict_new`) we can only match a function name.
The casm bytecode will be the same, but the hints-content will be implemented separately (like that function had a different hint that calls a single function that is implemented by our VM).

```
func dict_new() -> (res: DictAccess*) {
    %{
        // This entire hint will be something like an intrinsic call.
        __dict_new_hint_impl()
    %}
    ap += 1;
    return (res=cast([ap - 1], DictAccess*));
}
```

The downside is that it will rely on the external implementation.
If it ever changes, we'll need to adjust for that.

It will also cover only the stdlib provided by the cairo0, therefore it won't work for a user-provided custom hint inside their contracts.

I compiled a simple Cairo program to casm:
```cairo
fn main() -> u128 {
    let mut arr = ArrayTrait::<u128>::new();
    arr.append(100);
    let index_to_access =
        1; // Change this value to see different results, what would happen if the index doesn't exist?
    match arr.get(index_to_access) {
        Option::Some(x) => {
            *x
                .unbox() // Don't worry about * for now, if you are curious see Chapter 4.2 #desnap operator
        // It basically means "transform what get(idx) returned into a real value"
        },
        Option::None => { panic!("out of bounds") }
    }
}
```
Even this piece of code contains various cairo0-style pythonic hints:
```
// Memory comparison; looks simple to map
%{ memory[ap + 0] = memory[ap + -2] < memory[ap + -1] %}
```
```
// We can probably implement simple arithmetic like this?
// But it already looks like an expression calculator we're talking about.
%{ (memory[ap + 5], memory[ap + 6]) = divmod(memory[ap + -66], memory[ap + -1]) %}
```
```
// I wonder if % PRIME is a constant thing, maybe we don't need a generic modulo implementation.
%{ memory[ap + 0] = (memory[fp + -4] + memory[fp + -3]) % PRIME < 4294967296 %}
```
```
%{
  // This one looks more problematic, but maybe it's from some well-known function.
  (value, scalar) = (memory[ap + 3], 9304595970494411423921298675024789504)
  x = min(value // scalar, 340282366920938463463374607431768211455)
  y = value - x * scalar
  memory[ap + -2] = x
  memory[ap + -1] = y
%}
```
While I can believe that there is a limited set of these combinations (most of them are coming from the abovementioned core library), they may be dependent on the external code in the same way. If some Python code is being rewritten, we may stop recognizing it. Or even worse, it may start working incorrectly if our matcher is not good enough at catching illegal states (when it matches the code but misses a few nuances).

**Comment by quasilyte** [comment] 2024-01-17 11:05
Regarding dictionaries and their hints.
![image](https://github.com/NethermindEth/cairo-vm-go/assets/6286655/215793de-07e3-4ca2-adc2-e5f4ca57ed96)
https://github.com/starkware-libs/cairo/blob/894cfb25706e47882bff1f05a8043d586ea36bef/crates/cairo-lang-casm/src/hints/mod.rs#L388

It still looks like it's heavily dependent on pythonic hints.
AFAIK these declarations only used to produce a cairo0-style hints in the generated code while compiling the modern Cairo.
I don't think that Cairo compiler ever emits a hint like AllocFelt252Dict directly.
It's just a pretty name for a Cairo compiler to insert the necessary hint inside an inline Rust macro that generates some casm code.
![image](https://github.com/NethermindEth/cairo-vm-go/assets/6286655/61fb3935-68cc-4c8d-8519-13ea0c88741c)

**Closed** 2024-01-24 10:21 UTC
Labels: enhancement, vm hint
